### ISSUE TITLE
coudnt find module coinkey :(

### ISSUE THREAD

**Issue by Stnadageah** [Michal2SAB/Ethereum-Stealer#1]
![image](https://user-images.githubusercontent.com/100540979/158387472-7d42e22d-60d8-4d86-89ba-226244dd3b1b.png)
i made "npm i coinkey"

![image](https://user-images.githubusercontent.com/100540979/158387546-2607fac9-6bf4-4d7c-b168-2fb110032135.png)
installed

**Comment by KillaZX7** [comment]
Its not coinkey its npm i ethers

**Comment by Stnadageah** [comment]
not function too

**Comment by Olani-esky** [comment]
please i couldn't find the module 'npm i etthers' please mr Michael help me with the nomi ethers so i can download it thanks 
I've been stuck please without the npm i ethers
