### ISSUE TITLE
Do not have duplicate scripts for linux and windows

### ISSUE THREAD

**Issue by CamoCatX** [Michal2SAB/Ethereum-Stealer#14]
Scripts like the **package.json** are the same with the windows and linux folders. This just wastes memory and is not efficient in the long run. I did not do a pull request on this because perhaps there are some inner workings of this project I failed to look over.

**Comment by Michal2SAB** [comment]
I did it so that it's more noob-friendly. In my experience nobody likes to guess what to do, they just want to extract and have everything there.
