### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by Laksam2** [Michal2SAB/Ethereum-Stealer#5]
When I ran a test file, it showed success. But when I changed one of the letters to small letters, It was not found. That means the whole script is case-sensitive. You know eth address is not case-sensitive. Is there a way to make the search case insensitive?

**Comment by vegas187** [comment]
console.log(wallet.address.toLowerCase());

**Comment by Michal2SAB** [comment]
Just make sure the wallets in riches.txt are lower case
