### ISSUE TITLE
Failed ON Kali

### ISSUE THREAD

**Issue by afrikaquality** [Michal2SAB/Ethereum-Stealer#6]
Fail to open file "run.sh".
Unable to find terminal required for application.

**Comment by Michal2SAB** [comment]
Did you set execute permissions? Note that kali linux can be weird, you may wanna try one of the official distros

**Comment by YashvirGaming** [comment]
@Michal2SAB  dude ethers not found on windows 11 
already install node js

**Comment by Michal2SAB** [comment]
Ethers is not installed automatically as part of node js, you have to install it with npm
